[character]
success_symbol = "[îª«](bold #a6e3a1)"
error_symbol = "[ï€](bold #F02E6E)"

[directory]
truncation_length = 1
truncation_symbol = "./"
style = "fg:#94e2d5"

[package]
style = "red bold"
symbol = "ğŸš€ "

[git_branch]
symbol = "ïŠ–  "
style = "#F02E6E bold"

[git_status]
style = "#F02E6E bold"
